# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-06 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('link', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('disclaimer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('arts_ID', models.CharField(default='wvh10f6d9b91', editable=False, max_length=12)),
                ('arts_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', models.SlugField(unique=True)),
                ('distribution_restrictions', models.CharField(choices=[('default', 'Default'), ('limited', 'Limited'), ('none', 'None')], default='default', max_length=7)),
                ('document_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('alternate_tracking_number', models.CharField(max_length=200, null=True, unique=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('attachment', models.FileField(upload_to='Uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='arts_subclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GIDEP.Subclass'),
        ),
        migrations.AddField(
            model_name='document',
            name='arts_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GIDEP.AlertType'),
        ),
        migrations.AddField(
            model_name='document',
            name='arts_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
