# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-06 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIDEP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='arts_ID',
            field=models.CharField(default='enx84e74d380', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
        ),
    ]
