# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIDEP', '0002_auto_20190806_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='arts_ID',
            field=models.CharField(default='izxffbf92869', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
