# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-06 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIDEP', '0004_auto_20190806_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.AlterField(
            model_name='document',
            name='arts_ID',
            field=models.CharField(default='fqxg1d0625cb', editable=False, max_length=12),
        ),
    ]
